### ISSUE TITLE
ApplyLayer exit status 1 stdout:  stderr: open /var/log/lastlog: no such file or directory

### ISSUE THREAD

**Issue by vrutkovs** [goldmann/docker-squash#104]
Some files seem to be missing, as image cannot be loaded after squashing.

[Full log](https://gist.github.com/vrutkovs/9acbdd52ccd18150b5e3e5e2ea7ee7aa)

**Comment by goldmann** [comment]
I got the image offline, investigating.

**Comment by goldmann** [comment]
Found the cause. Since we merge layers from the end (newest) we add a symlink (`/var/log`) to a non-existent location (`/data/var/log`). Later we try to add some files under the `/var/log/` path. Tar will accept anything, but at the extraction time Docker will complain because it doesn't know where to extract it (there is no `/data/var/log` path).

**Comment by goldmann** [comment]
A proposed fix has been submitted as a PR #105.
