### ISSUE TITLE
Add option for squashing all layers starting from the base image

### ISSUE THREAD

**Issue by TheFriendlyCoder** [goldmann/docker-squash#131]
Currently there is an option to specify the hash of a specific layer from which you want to begin squashing, but it would be convenient if there was some short-hand way to detect which hash represents the base image and use that value automatically.

The most obvious use case for this would be for automated systems which build new images from Dockerfiles and publish the new images to an artifact repository. It would be nice to be able to do something like 'docker-squash --from-base-image' and have all of the commits generated by the current docker file squashed into a single commit.

**Comment by TheFriendlyCoder** [comment]
TIP: One 'hack' that I just came up with was to write a small Python script to make use of the docker-py API to extract the history from an image and locate the latest one with a 'tag' associated with it, and return the hash / id for that layer. I'm not sure how robust this logic is, but in my ad-hoc tests this results in the layer ID for the layer of the base image used by the current docker file, which in turn can be passed to the '-f' parameter of docker-squash.

Here's a little snippet of what I've done:

```
# get_hash.py

# ... put code here for parsing image / tag name from command line

from docker import Client
def get_hash(image_name):
    cli = Client()
    hist = cli.history(image_name)
    for i in hist:
        # NOTE: Ignore the first layer in case it has been tagged as part of the Dockerfile build process 
        if i is not hist[0]:
            if i['Tags']:
                return i
    return None
```

And here's an example of how one might use this (requires a *nix shell):

```docker-squash -f `./get_hash.py old_tag_name` -t my_new_tag old_tag_name```

**Comment by goldmann** [comment]
Hey, thanks for the code. Unfortunately it has at least few issues:

1. Base image can contain more than one layer.
2. History can be empty and contain `<missing>` ID's which will prevent you from getting the right layer.

It's much more complicated than this, so my take on this is to not implement such feature. Every image can be different and only the user knows what needs to be done. Best idea is to script it based on your requirements and invoke `docker-squash` with proper arguments. This is best we can do.

Additionally my POV is that squashing all layers in an image, including base and other intermediate images is a bad pattern which should be avoided. Best idea is to squash only the content of a single Dockerfile.

Feel free to continue the chat, but I'm going to close this issue as I don't want to implement it because it's impossible to do so.
