### ISSUE TITLE
Squashing an image that is already squashed causes a nonzero exit code

### ISSUE THREAD

**Issue by jamesmallen** [goldmann/docker-squash#141]
We've integrated docker-squash into our pipeline for certain Docker images. If an image has already been squashed, though, docker-squash exits with an exit code of 0, which indicates an error.

It would be nice if this particular situation wasn't considered an error, or at least offer a command-line flag that would print a message to the INFO or WARNING logger but not `exit 1`.

A workaround for this problem would be to skip error checking for this part of our pipeline.

**Comment by goldmann** [comment]
Oh, that's unfortunate. I'll try to take a look at this. Thanks for the info!

**Comment by jamesmallen** [comment]
I'm happy to do a PR if you have any preference for the desired behavior. My inclination would be to add a command line option, in case anyone is depending on this situation exiting with code 1, although I don't necessarily want to set a precedent of throwing in a ton of optional flags.

**Comment by goldmann** [comment]
Nah, an additional switch is not a good solution IMHO. Can you paste log of an execution where the image was already squashed?

**Comment by jamesmallen** [comment]
```
2017-02-28 21:40:54,033 root         INFO     docker-squash version 1.0.5, Docker 78d1802, API 1.24...
2017-02-28 21:40:54,033 root         INFO     Using v2 image format
2017-02-28 21:40:54,039 root         INFO     Old image has 1 layers
2017-02-28 21:40:54,039 root         INFO     Checking if squashing is necessary...
2017-02-28 21:40:54,039 root         ERROR    1 layer(s) in this image marked to squash, no squashing is required
2017-02-28 21:40:54,040 root         ERROR    Execution failed, consult logs above. If you think this is our fault, please file an issue: https://github.com/goldmann/docker-squash/issues, thanks!
```

**Comment by goldmann** [comment]
Thank you, I'll change this to warning and exit gracefully.

**Comment by goldmann** [comment]
I was looking into this today. It looked as an easy fix, but after all I ended up with a bigger refactoring :) While working I ended wup with some doubts if changing it to warning is a good thing. Here are a few issues I can see:

1. When using this tool as a library - it'll not break the pipeline and some other tool may think that the image was in fact squashed, but it was not. This is slightly different look at your case. You may have some post processing that you do not want to run when image was not squashed.
2. If we return the ID - should be also tag the original image if the tag name was provided or not?

I'm thinking now more about raising a specific Error instead of returning silently, for example: `SquashUnnecessary`. This will not break the current behavior, but it'll enable you to ignore this error, if you want.

/cc @twaugh @vrutkovs

**Comment by twaugh** [comment]
I'd be happy with `SquashUnnecessary`. I'd noticed this behaviour too when playing with atomic-reactor imagebuilder builds.

**Comment by goldmann** [comment]
@jamesmallen What do you think about the proposal above?

**Comment by twaugh** [comment]
@admiller, any thoughts/objections?

**Comment by jamesmallen** [comment]
@goldmann I think this sounds very reasonable, as long as there is a specific exit code from the cli for `SquashUnnecessary`. Thanks!

**Comment by goldmann** [comment]
@jamesmallen Good point on the exit code. I guess the general one `-1` doesn't work for you, so I can take next available; `-2`.

**Comment by maxamillion** [comment]
Sounds good. +1
