### ISSUE TITLE
Can docker-squash use multi cores?

### ISSUE THREAD

**Issue by tarjintor** [goldmann/docker-squash#196]
I find docker-squash can only use 1 core at 100%,this is very slow for large image about 100G
I use
`docker-squash --help`
didn't find any clue
and I search the issus already exists too

**Comment by goldmann** [comment]
Which part of the process takes only a single core? Some parts are outside of our control. For example exporting a Docker image is not multi-threaded in daemon and this will take some time. I suspect this is what you see. This is before the squash tool even starts to do it's job.

Could it be this in your case?

**Comment by tarjintor** [comment]
@goldmann I read the source,there are two phrase takes most of the times

1. save image to tmp dir
2.squash layer by layer

I guess for 1 there is no solution
Not sure if we can design an algrithim to parallel 2,

**Comment by goldmann** [comment]
Yah, we cannot do it parallel unfortunately since layers influence layers below. Saying this, I did some improvements there to cheat a bit. It was much slower previously.

Saying this, the root of the issue is that you have a very big image as the input, which suggests that there could be done some optimization in Dockerfile itself, before docker-squash kicks in.

**Comment by tarjintor** [comment]
OK,thanks
