### ISSUE TITLE
Is docker-squash still maintained?

### ISSUE THREAD

**Issue by hartwork** [goldmann/docker-squash#203]
Hi!

I noticed the last commit on `master` is from October 2019. Is docker-squash still maintained, is there a note on its current status somewhere?

Thanks and best, Sebastian

**Comment by goldmann** [comment]
Well, it just works (tm). We've been using it in production since 2016 without issues and we build hundreds of images every day.

**Comment by hartwork** [comment]
Hi @goldmann thanks for your reply. If it works well for your current subset of operations in one particular environment is — while related — a bit of a different question than being maintained. What about the 17 other open issues, 3 pull requests and 4 non-master branches? Skip reading through the issues from latest to oldest a bit, I have already seen 5 that have never been answered to.

**Comment by goldmann** [comment]
Hey @hartwork!

Because there are no immediate needs from me or (my company), I'm not focusing my time on this project that much. This is correct. I don't consider this project as unmaintained though.

Regarding issues and pull requests - I think this is a regular open source project and usual rules apply here as well. People are free to open tickets and submit proposal for changes as pull request. And this is what people do. And this is fine. For example all PR's are reviewed, but changes were not applied there. I need to close them in fact. Considering the fact that there is still pretty big interest in this project, I would personally expect a bit more community involvement in maintenance or help. But expectations are almost always different from reality :)

Does this help?

**Comment by hartwork** [comment]
Hi @goldmann,

I'm a free software developer and maintainer upstream and a distro packager downstream myself, and I did not come here with an intention to argue with you, but to understand the situation. With that said, we seem to have a different understanding of what "unmaintained" means. I have not seen _any_ software that would not need any fixes since 2019 and that plus >=5 unanswered issues are not on the "maintained" end of the spectrum in _my_ book. So we can agree to disagree I suppose. Thanks for explaining the situation, I think that transparency is good for all current and future users.

Best, Sebastian

**Comment by goldmann** [comment]
No worries, I'm open to feedback. Thanks for discussion!
