### ISSUE TITLE
from-layer default behavior

### ISSUE THREAD

**Issue by R-omk** [goldmann/docker-squash#96]
Perhaps it would be better to find the first layer in the FROM clause and  squash only after it, instead of squashing all layer by default.

**Comment by goldmann** [comment]
We are unable to find the correct layer, Docker **image** does not have any information about what was the `FROM` layer. In other words - instruction in `FROM` is just another layer (the image ID we base from).

**Comment by R-omk** [comment]
Its really, but in this implementation 
https://github.com/jwilder/docker-squash/blob/master/main.go#L107
used some magic!

**Comment by goldmann** [comment]
But this assumes something which is not really true in many cases:
https://github.com/jwilder/docker-squash/blob/d78be897bab28dc6419d89178f841fae2ecb0412/export.go#L295

**Comment by R-omk** [comment]
Ok! 
Now we just parse `Dockerfile`  in our custom docker builder
```
  from_line_parts=($(cat Dockerfile | grep "^FROM "))
  from_image=${from_line_parts[1]}
```

and use like `--from-layer ${from_image}`. Its work fine!

**Comment by goldmann** [comment]
This is what we do too :)

In this case, I'll close this issue.

**Comment by goldmann** [comment]
Sorry couldn't resist:

```
--from-layer `grep ^FROM Dockerfile | awk '{print $2}'`
```

**Comment by joonas-fi** [comment]
I was just about to open an issue about this. Just goes to show, one should always search first. ;)

Thanks @R-omk for the shell magic, I'll use that one as well.

@goldmann: maybe put this advice on the docs somewhere (or even better, `--help` output as a tip?), since I think this is what everybody wants anyway.

It is relatively painful to come to this far to find suggestion for how to do this, when jwilder's docker-squash does the right thing by default (arguably, with some magic that does not always work? And his docker-squash sadly seems unusable (just doesn't seem to work), so that's why I came here. BTW thanks! :)

As for Docker, I fucking love the problems it solves but as for the current Dockerfile building behaviour I think it's disgustingly unusable. (LAYERS! MORE LAYERS! OH YES YOU HAVE TO PUSH AND PULL THE LAYERS EVERYHWERE THAT SHOULD ONLY BE FOR BUILD CACHING PURPOSES OH MY GOD THIS IS GENIOUS IDEA)

This squash behaviour or more saner difference between layer model for build caching purposes and versus output layer model should have been there from the start.

**Comment by goldmann** [comment]
I think readme would be a good place to put this information. Feel free to open a PR :)
